### ISSUE TITLE
create_certs fails due to missing hail_version

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/hail#106]
Running step 3 (`tls/create_certs.py`) in https://github.com/hail-is/hail/blob/main/dev-docs/tls-cookbook.md fails because `hail/python/hailtop/hail_version` doesn't exist in a standard cloned repo. It's possible to work around this by setting a dummy version, but maybe there's a better way to handle the version dependency?

**Comment by illusional** [comment]
Is it enough to run the make hail_version script?

**Comment by lgruen** [comment]
Thanks, `make -C hail python/hailtop/hail_version` seems to do the trick. I'll update the docs.
