### ISSUE TITLE
Issue with analysis-runner version pin during server release

### ISSUE THREAD

**Issue by illusional** [populationgenomics/hail#141]
FYI @vladsaveliev: https://github.com/populationgenomics/analysis-runner/runs/5216589345?check_suite_focus=true

Looks like an issue with this line, where `env.version` resolves to `$pip_version`: https://github.com/populationgenomics/hail/blob/3b5a40aa89825104050c98df525ec68d68b1ca1a/.github/workflows/package.yaml#L67

**Comment by lgruen** [comment]
This is obsolete, right?

**Comment by illusional** [comment]
Yep obselete, closing now
