### ISSUE TITLE
Always mount deploy-config

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/hail#18]
See https://github.com/hail-is/hail/pull/9907 for context.

This will allow us to clean up https://github.com/populationgenomics/analysis-runner/blob/main/driver/Dockerfile#L16.

**Comment by illusional** [comment]
As discussed, it seems this was addressed in https://github.com/hail-is/hail/pull/9848: 

https://github.com/populationgenomics/hail/blob/fd2ba800d9e82e3a1d2fb2f1d90b7ea03973b3d5/batch/batch/front_end/front_end.py#L729-L733

The `mount_tokens` flag is set to True in this commit by @lgruen: https://github.com/populationgenomics/hail/commit/a2e07f6c8c69a57c999ab0821334fe1af9f20b5f.

I was able to trigger it with:

```python
import hailtop.batch as hb

"""
cpg-michael-hail-dev
"""

backend = hb.ServiceBackend()

b = hb.Batch(name="batchception", backend=backend)
j = b.new_job(name="batchception-trigger")
j.image("michaelfranklin/hail-batch:no-config")

j.command(f"""
export HAIL_DEPLOY_CONFIG_FILE=/deploy-config/deploy-config.json

cat <<EOT >> /opt/script.py

def submit_inner_batch_run():
    import hailtop.batch as hb

    # Using backend=None
    backend = hb.ServiceBackend(billing_project="michaelfranklin-trial", bucket="cpg-michael-hail-dev")

    inner_batch = hb.Batch(name="inner-batchception", backend=backend)
    inner_job = inner_batch.new_job("hello-world")
    inner_job.command("echo 'Hello, (inner) World!'")
    inner_batch.run()

if __name__ == "__main__":
    submit_inner_batch_run()
EOT

python /opt/script.py
""")

b.run()
```

![image](https://user-images.githubusercontent.com/22381693/106963243-6ad38580-6794-11eb-9776-a938ef9ead8f.png)

And here's the corresponding fix to the analysis-runner: https://github.com/populationgenomics/analysis-runner/pull/9
