### ISSUE TITLE
Upstream the Artifact Registry change

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/hail#42]
We should upstream these changes to reduce the divergence of our fork.

See https://github.com/populationgenomics/hail/pull/29, https://github.com/populationgenomics/hail/pull/40 https://github.com/populationgenomics/hail/pull/41, #46

**Comment by vladsaveliev** [comment]
We would need to merge [infra-1](https://github.com/cseed/hail/tree/infra-1) first. But I guess because `infra-1` was done really quickly, it might need additional clean-up work to be upstream-ready?

**Comment by vladsaveliev** [comment]
infra-1 is [merged](https://github.com/hail-is/hail/pull/9713)!

Created an upstream PR for the AR: https://github.com/hail-is/hail/pull/10107
